name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pytorch=1.9.0
  - tensorboard=2.4.0
  - tensorboardx=2.1
  - termcolor
  - pip:
    - git+https://github.com/minerllabs/minerl
    - coloredlogs
    - matplotlib
    - aicrowd-api
    - aicrowd-gym
    - gym3
    - attrs
    - gym
    - wandb
    - hydra-core==1.0
    - tensorboardX
    - stable_baselines3
    - tk
#    - -e ./learning-from-human-preferences
